cache:
  key: '$CI_BUILD_REF_NAME node:8-alpine'
  paths:
    - node_modules/

stages:
  - test

test:
  stage: deploy
  before_script:
    - apk add --update bash
    - apk add --update git && rm -rf /tmp/* /var/cache/apk/*
    - npm install
  script:
    - npm run lint
  artifacts:
    paths:
      - server/
      - public/
