cache:
  key: '$CI_BUILD_REF_NAME node:8-alpine'
  paths:
    - node_modules/

stages:
  - test

docker-test:
  stage: test
  image: node:8
  before_script:
    - apk add --update bash
    - apk add --update git && rm -rf /tmp/* /var/cache/apk/*
    - npm install -g eslint
    - npm install --no-cache
  script:
    - npm run lint
  artifacts:
    paths:
      - server/
      - public/
  only:
    - deploy
