cache:
  key: '$CI_BUILD_REF_NAME node:8'
  paths:
    - node_modules/

stages:
  - test
  - release

test:
  stage: test
  image: node:8
  only:
    - deploy
  before_script:
    - rm -rf /tmp/*
    - npm install -g eslint
    - npm install --no-cache
  script:
    - npm run lint

release:
  stage: release
  image: docker:latest
  only:
    - deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
before_script:
    - docker version
    - docker info
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"