stages:
  - test

docker-test:
  stage: test
  image: node:8
  before_script:
    - rm -rf /tmp/*
    - npm install -g eslint
    - npm install --no-cache
  script:
    - eslint '**/*.{js,jsx}' --quiet
  only:
    - deploy
