cache:
  key: '$CI_BUILD_REF_NAME node:8'
  paths:
    - node_modules/

stages:
  - test

docker-test:
  stage: test
  image: node:8
  before_script:
    - npm install --cache /tmp/empty-cache
    - npm install -g eslint
    - npm install --only=dev
  script:
    - eslint '**/*.{js,jsx}' --quiet
  only:
    - deploy
