version: '3'

volumes:
  node_modules:
  postgres:

networks:
  postgres:
    driver: bridge

services:
  node:
    restart: always
    image: registry.gitlab.com/longnt189/restful-api-base:latest
    volumes:
      - node_modules:/usr/app/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/Codebase
    ports:
      - '8080:8080'
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Codebase
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
  nginx:
    image: nginx:latest
    links:
      - node
    ports:
      - '80:80'
      - '443:443'
